# Inspired by: https://github.com/lervag/vimtex/blob/master/.github/workflows/main.yml
name: Test
on: [pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - uses: actions/checkout@v1
      - name: Test with neovim
        run: nvim --version
      - name: Test syntax
        run: make test-syntax
